apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Helm intro</title>
    </head>
    <body style="background: {{ .Values.nginx.backgroundColor }};">
      <center>
        <h1>Welcome to the helm intro!</h1>
        <p>...and happy helming</p>
      </center>
    </body>
    </html>
